### ISSUE TITLE
Unable to register carina-demo from launchers (for forked carina)

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2240] opened 2020-10-06 17:02 UTC
**Steps to reproduce**

1. Install and start zebrunner ce
2. Log in to Reporting
3. Click Test Launchers
4. Remove default carina-demo
5. Click Add Repo and enter->organization + carina-demo repo
6. Scan 

**Actual behavior**
Carina-demo repo is empty. In jenkins - organization is not created 

**Expected behavior (if known)**
carina-demo contains all required jobs

**Environment**

ui: 1.12.1
server: 1.12.2

<img width="1021" alt="Screen Shot 2020-10-06 at 7 52 44 PM" src="https://user-images.githubusercontent.com/32964663/95235719-9bb7a400-080e-11eb-9634-14cd52e60591.png">

**Comment by vdelendik** [comment] 2021-03-09 17:17
closing as can't reproduce. @okamara please retest using latest zebrunner from develop branch

**Closed by vdelendik** 2021-03-09 17:17 UTC
Labels: enhancement

**Comment by okamara** [comment] 2021-03-09 18:02
Re-verified, can't repro.
