### ISSUE TITLE
Set 'run_exists=true' when rerun

### ISSUE THREAD

**Issue by deNatallia** [zebrunner/reporting#1794] opened 2019-10-15 13:57 UTC
Choose run in Zafira that has already been written in testrail.
Click 'Rerun' it.

**Expected result:** existing test run is updated in testrail
**Actual result :** new run is created in testrail

Because of parameter 'run_exists' is FALSE by default. So it should be set to TRUE for rerunning.

**Comment by nsidorevich** [comment] 2019-10-28 08:20
Not reproduced since was already fixed by @tsvrko

**Comment by deNatallia** [comment] 2019-11-20 10:29
It is still repro.
1. Run any job with parameter 'run_exists' = false and 'testrail_enabled' = true -> Results were published in testrail in run with name 'Testrun_1'.
2. Rerun this run using zafira

**Expected result:** Results were updated in 'Testrun_1'

**Actual result:** New testrun 'Testrun_1' with results was created

**Comment by vdelendik** [comment] 2021-09-29 23:08
closing as already fixed in pro version. CE integration with testrail is too limited now

**Closed by vdelendik** 2021-09-29 23:08 UTC
