### ISSUE TITLE
The test suite filter does not work in the test runs viewer

### ISSUE THREAD

**Issue by FredVaugeois** [zebrunner/reporting#2272] opened 2020-12-18 13:53 UTC
When filtering by Test Suite, it simply does not work:

![image](https://user-images.githubusercontent.com/26579806/102621803-1e61b700-410e-11eb-98e2-c5f1c0822933.png)

It would also be nice, as said in an earlier [issue of mine](https://github.com/zebrunner/reporting/issues/2224), to be able to remove 'local' runs with this filter.

Since the older issue isn't marked as resolved, but we do seem to have the option of filtering by test suite (even tough it doesn't work for now), I added this new one to make sure it was addressed. This issue can be closed and marked as a duplicate of [2224](https://github.com/zebrunner/reporting/issues/2224) if you want.

**Comment by vdelendik** [comment] 2021-02-24 23:05
closing as dupe of #2224

**Closed by vdelendik** 2021-02-24 23:05 UTC
