### ISSUE TITLE
I got "-1" test case for ios test run via zebrunner 

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#1969] opened 2019-12-24 14:42 UTC
**Description**
Start Run for ios Safari as user

**Steps to reproduce**

1. Launch test run
2. Test run is completed. Open test results
3. Verify each Red test result and mark is Passed

**Actual behavior**
In the top of the page I see that the number of cases is "-1"(see image)

**Expected behavior (if known)**
I see that the number of cases is "0"

**Environment**
https://qps.zebrunner.com/

<img width="282" alt="Screen Shot 2019-12-24 at 12 37 07 PM" src="https://user-images.githubusercontent.com/32964663/71417134-cb792f00-2674-11ea-8c1c-2ea8e1d429e1.png">

**Comment by danymill** [comment] 2019-12-31 07:52
It is BE task. For example, data from WebSocket (testRunStatistics) is:
```
testRunId: 791
passed: 6
failed: -1
failedAsKnown: 0
failedAsBlocker: 0
skipped: 0
inProgress: 0
aborted: 0
queued: 0
reviewed: false
```

But before test status changes we had `passed: 4` & `failed: 1`

**Comment by vdelendik** [comment] 2020-10-08 09:39
it should be fixed indirectly

**Closed by vdelendik** 2020-10-08 09:39 UTC
Labels: status: ready-for-work, type: bug

**Comment by okamara** [comment] 2020-10-08 14:24
It should be tested on customer's side

**Comment by vdelendik** [comment] 2020-10-12 13:31
closing as can't reproduce
