### ISSUE TITLE
Integration:404 error after rediraction to reporting

### ISSUE THREAD

**Issue by dhreben** [zebrunner/reporting#2278] opened 2021-01-14 18:37 UTC
**Test scenario:**

1.Git clone from develop
2.Run ./zebrunner.sh setup
3.Open Jenkins
4.Run RegisterOrganization
5.Run RegisterRepository
6.Run API-Demo-Test
7.Open Zafira report
8.Click on Jira link to test DEMO-0004

**Actual result** : 404 page is opened

ui: 1.18.0.95-SNAPSHOT
server: 1.18.0.116-SNAPSHOT

<img width="1283" alt="Screenshot 2021-01-14 at 21 24 37" src="https://user-images.githubusercontent.com/50950954/104632619-077f9780-56af-11eb-8eb1-c7d4bb1791fe.png">

**Comment by vdelendik** [comment] 2021-02-24 23:30
@dhreben, closing as not a bug. use-case with jira ticket can be tested only after enabling actual integration with Jira. Without it links are invalid as they refer to nothing...

**Closed by vdelendik** 2021-02-24 23:30 UTC
Labels: bug, invalid

**Comment by dhreben** [comment] 2021-02-25 10:34
Closed. Not a bug.It works with enabling  actual integration with Jira.
