### ISSUE TITLE
Reporting-service is not started on Mac

### ISSUE THREAD

**Issue by okamara** [zebrunner/reporting#2296] opened 2021-06-15 09:56 UTC
**Precondition**
Install docker
Git is installed

**Steps to reproduce**

1.  git clone --recurse-submodule --branch develop https://github.com/zebrunner/zebrunner.git
2. ./zebrunner.sh setup and start

**Actual behavior**
 reporting-service is not started

**Expected behavior (if known)**
 reporting-service is started

**Environment**
zebrunner ce from develop branch

**Attachments**
<img width="201" alt="Снимок экрана 2021-06-15 в 12 50 06" src="https://user-images.githubusercontent.com/32964663/122032370-3de54e00-cdd8-11eb-8125-e5e4f9d3a2ac.png">

**Additional context**
Exception in thread "main" java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

at java.base/java.lang.reflect.Method.invoke(Unknown Source)

at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)

at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)

at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)

at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

Caused by: java.lang.NoClassDefFoundError: org/springframework/core/env/PropertySource

at com.zebrunner.reporting.ApplicationInitializer.main(ApplicationInitializer.java:13)

... 8 more

Caused by: java.lang.ClassNotFoundException: org.springframework.core.env.PropertySource

at java.base/java.net.URLClassLoader.findClass(Unknown Source)

at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151)

at java.base/java.lang.ClassLoader.loadClass(Unknown Source)

... 9 more

**Comment by vdelendik** [comment] 2021-09-29 23:04
closed as dupe of https://github.com/zebrunner/reporting/issues/2250

**Closed by vdelendik** 2021-09-29 23:04 UTC
Labels: bug, duplicate
